export const bundles = [
{
"name": "Wüstenkit",
"medikamente": [
"Loperamid",
"Elotrans",
"Vomex-A",
"Paracetamol",
"Aspirin",
"Ibuprofen",
"Cetirizin",
"Fenistil",
"Sonnencreme",
"Bepanthen",
"Insektenstichheiler",
"Autan",
"Pflaster",
"Wasserdichte Pflaster",
"Verbandsset",
"Superpep",
"Electrolyte",
"Pinzette",
"Wunddesinfektionsmittel",
"Fieberthermometer",
"Blasenpflaster",
"Kühlpad",
"Wasserfilter Tabletten",
"Kleine Taschenlampe"
],
"beschreibung": "Für Wüstenabenteuer und Expeditionen — vorbereitet auf Hitze, Sonne und lange Tage unterwegs. 24-teilig, apothekengepackt.",
"img": "/bundles/city_1920.jpg"
},

{
"name": "Tropen Kit",
"medikamente": [
"Loperamid",
"Elotrans",
"Vomex-A",
"Paracetamol",
"Aspirin",
"Ibuprofen",
"Cetirizin",
"Fenistil",
"Sonnencreme",
"Bepanthen",
"Insektenstichheiler",
"Autan",
"Pflaster",
"Wasserdichte Pflaster",
"Verbandsset",
"Superpep",
"Electrolyte",
"Zeckenzange",
"Wunddesinfektionsmittel",
"Fieberthermometer",
"Kochsalzaugentropfen",
"Kochsalz Nasenspray",
"Wasserfilter Tabletten",
"Moskitonetz"
],
"beschreibung": "Für tropische Entdeckungsreisen — Schutz und Versorgung in warmen, feuchten Klimazonen. 24-teilig, apothekengepackt.",
"img": "/bundles/tropical_1920.jpg"
},

{
"name": "Monsun Kit",
"medikamente": [
"Loperamid",
"Elotrans",
"Vomex-A",
"Paracetamol",
"Aspirin",
"Ibuprofen",
"Cetirizin",
"Fenistil",
"Sonnencreme",
"Bepanthen",
"Insektenstichheiler",
"Autan",
"Pflaster",
"Wasserdichte Pflaster",
"Verbandsset",
"Superpep",
"Electrolyte",
"Zeckenzange",
"Wunddesinfektionsmittel",
"Fieberthermometer",
"Kochsalzaugentropfen",
"Kochsalz Nasenspray",
"Moskitonetz",
"Wasserfilter Tabletten",
"einmal Regenschutz"
],
"beschreibung": "Für Reisen in der Regenzeit — zuverlässige Versorgung bei Feuchtigkeit, Insekten und wechselhaften Bedingungen. 25-teilig, apothekengepackt.",
"img": "/bundles/monsun_1920.jpg"
},

{
"name": "Hochgebirgs Kit",
"medikamente": [
"Loperamid",
"Elotrans",
"Vomex-A",
"Paracetamol",
"Aspirin",
"Ibuprofen",
"Cetirizin",
"Fenistil",
"Sonnencreme",
"Bepanthen",
"Insektenstichheiler",
"Autan",
"Pflaster",
"Wasserdichte Pflaster",
"Verbandsset",
"Superpep",
"Electrolyte",
"Zeckenzange",
"Wunddesinfektionsmittel",
"Fieberthermometer",
"Kochsalzaugentropfen",
"Kochsalz Nasenspray",
"Kälteschutzcreme",
"Lippenbalsam mit UV Schutz",
"Wärmekompressen",
"Blasenpflaster"
],
"beschreibung": "Für Trekking und Abenteuer in großen Höhen — Schutz bei Kälte, starker UV-Strahlung und anspruchsvollen Bedingungen. 26-teilig, apothekengepackt.",
"img": "/bundles/mountain_1920.jpg"
},

{
"name": "Kaltklima Kit",
"medikamente": [
"Loperamid",
"Elotrans",
"Vomex-A",
"Paracetamol",
"Aspirin",
"Ibuprofen",
"Cetirizin",
"Fenistil",
"Sonnencreme",
"Bepanthen",
"Insektenstichheiler",
"Autan",
"Pflaster",
"Wasserdichte Pflaster",
"Verbandsset",
"Superpep",
"Electrolyte",
"Zeckenzange",
"Wunddesinfektionsmittel",
"Fieberthermometer",
"Kochsalzaugentropfen",
"Kochsalz Nasenspray",
"Kälteschutzcreme",
"Lippenbalsam mit UV Schutz",
"Wärmekompressen",
"Blasenpflaster",
"Rettungsdecke"
],
"beschreibung": "Für kalte Reiseziele und Winterabenteuer — bestens vorbereitet auf Kälte, trockene Luft und Outdoor-Belastungen. 27-teilig, apothekengepackt.",
"img": "/bundles/snow_1920.jpg"
},

{
"name": "Wander Kit",
"medikamente": [
"Sonnencreme",
"Voltaren",
"Autan",
"Wasserdichte Pflaster",
"Verbandsset",
"Elektrolyte",
"Blasenpflaster",
"Elastische Binde",
"Wunddesinfektion",
"Pinzette",
"Ibuprofen"
],
"beschreibung": "Der Begleiter für jede Wanderung — schnelle Hilfe bei Blasen, Muskelbeschwerden und kleinen Verletzungen. 11-teilig, apothekengepackt.",
"img": "/bundles/hiking_1920.jpg"
},

{
"name": "Städte Reisen Kit",
"medikamente": [
"Loperamid",
"Elotrans",
"Vomex A",
"Paracetamol",
"Ibuprofen",
"Cetirizin",
"Fenistil",
"Sonnencreme",
"Bepanthen",
"Voltaren",
"Pflaster",
"Fieberthermometer",
"Pinzette",
"Desinfektionsmittel",
"Autan"
],
"beschreibung": "Perfekt für Städtetrips und Kurzreisen — die wichtigsten Helfer für typische Beschwerden unterwegs. 15-teilig, apothekengepackt.",
"img": "/bundles/city_1920.jpg"
},

{
"name": "Welten Kit",
"medikamente": [
"Loperamid",
"Elotrans",
"Vomex-A",
"Paracetamol",
"Aspirin",
"Ibuprofen",
"Cetirizin",
"Fenistil",
"Sonnencreme",
"Bepanthen",
"Insektenstichheiler",
"Autan",
"Pflaster",
"Wasserdichte Pflaster",
"Verbandsset",
"Superpep",
"Electrolyte",
"Zeckenzange",
"Wunddesinfektionsmittel",
"Fieberthermometer",
"Kochsalzaugentropfen",
"Kochsalz Nasenspray"
],
"beschreibung": "Der Allrounder für jede Reise — zuverlässige Versorgung für die häufigsten Beschwerden weltweit. 22-teilig, apothekengepackt.",
"img": "/bundles/world_1920.jpg"
}
]