// Generated by `prisma-composer dev` — overwritten on every run; do not
// edit by hand. Independently runnable from "/home/helixlit/voyamed":
//
//   alchemy deploy .prisma-composer/dev/alchemy.run.ts --stage dev
//
// bisects a CLI bug from an Alchemy bug (deploy-cli.md § Implementation decisions).
import * as path from 'node:path';
import { deserializeContainers } from '@prisma/composer/config';
import { lower } from '@prisma/composer/deploy';
import { DEV_DIR, localTargetProviders, resolveLocalTargets } from '@prisma/composer/local-target';
import { localState } from 'alchemy/State/LocalState';
import config from "../../prisma-composer.config.ts";
import app from "../../module.ts";

const containers = deserializeContainers(config.extensions, process.env);
const resolved = await resolveLocalTargets(config);
const devDir = path.join(process.cwd(), DEV_DIR);

export default lower(app, config, {
  name: "voyamed",
  bundles: {
    "catalog.service": { dir: "/home/helixlit/voyamed/.prisma-composer/artifacts/catalog.service", entry: "bundle/server.mjs" },
    "storefront": { dir: "/home/helixlit/voyamed/.prisma-composer/artifacts/storefront", entry: "bundle/modules/storefront/server.js" },
  },
  providers: localTargetProviders(resolved, containers, devDir),
  state: localState(),
});
